import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :oriio_web, OriioWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: System.get_env("PORT") || 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "sSBHgentSG0KsooiEtZK+1DVY2jkijFm1QTLEXBIpTRq1D1conx5BAPvZC2s2lHG",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]

config :oriio, :base_file_url, "http://localhost:4200"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :oriio_web, OriioWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/oriio_web/(live|views)/.*(ex)$",
      ~r"lib/oriio_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# File storage engine
config :oriio, :file_storage,
  storage_engine: "local",
  access_key: System.get_env("ORIIO_FILE_STORAGE_ACCESS_KEY"),
  secret_key: System.get_env("ORIIO_FILE_STORAGE_SECRET_KEY"),
  region: System.get_env("ORIIO_FILE_STORAGE_REGION"),
  bucket: System.get_env("ORIIO_FILE_STORAGE_BUCKET")

config :oriio_web,
       :auth_secret_key,
       "KN58vmkzeiUFMIo8nmv4OHagbIDXAzciZmyZ2lp3gXZHs4wlcJ1IElyQkuqGk9L9"

config :oriio,
       :signed_upload_secret_key,
       "3ggV3CQIWN3hOhjH23iCulxA4xdHG9Egba4xGlyXFNTCKjuxOeUoHxy9qXqdQNEo"
