apiVersion: v1
kind: Service
metadata:
  name: mahi
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: mahi
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mahi-deployment
  labels:
    app: mahi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mahi
  template:
    metadata:
      labels:
        app: mahi
    spec:
      containers:
        - name: mahi
          image: registry.digitalocean.com/mahi-repo/mahi
          ports:
          - containerPort: 8080
          env:
            - name: SECRET_KEY_BASE
              value: FGwH/tyjHh4SSv/hcqRnvcPF3ffqxMPaiwB52hdW/A6TDxY82nKa1MWrtuC7wpmq
            - name: MAHI_FILE_STORAGE_ENGINE
              value: s3-compatible
            - name: MAHI_FILE_STORAGE_ACCESS_KEY
              value: AKIA53ZJZHZMFRYWSOTO
            - name: MAHI_FILE_STORAGE_SECRET_KEY
              value: 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
            - name: MAHI_FILE_STORAGE_REGION
              value: us-east-2 
            - name: FLY_APP_NAME
              value: mahi    
            - name: MAHI_FILE_STORAGE_BUCKET
              value: mahi-my-4-app-2672      
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      imagePullSecrets:
      - name: mahi-repo
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "921a50d6-7e57-42cb-adb9-3bb7dafa00ba"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  type: LoadBalancer
  selector:
    app: nginx-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080