name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: 
      - main
      - staging
      - release

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.13.2' 
        otp-version: '24' 
    - name: Update packages
      run: sudo apt-get update    
    - name: Update apt
      env:
        DEBIAN_FRONTEND: noninteractive
      run: 
        sudo apt-get update -qq -o Acquire::Retries=3
    - name: Install libvips
      env:
        DEBIAN_FRONTEND: noninteractive
      run:
        # we only need the library
        sudo apt-get install --fix-missing -qq -o Acquire::Retries=3
          build-essential \
          locales \
          gcc \
          erlang-dev \
          libvips \
          libvips-dev \ 
          libvips-tools         
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Check for warnings
      run: mix compile --warnings-as-errors    
    - name: Run Credo
      run: mix credo --strict
    - name: Run Dialyzer
      run: mix dialzyer    
    - name: Run tests
      run: mix test